AllCops:
  TargetRubyVersion: 3.1.0
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - "lib/warped/queries/paginate.rb"

Metrics/AbcSize:
  Exclude:
    - "lib/warped/controllers/filterable/ui.rb"
    - "lib/warped/controllers/sortable/ui.rb"
    - "lib/warped/emails/components/**/*.rb"
    - "lib/warped/queries/filter.rb"

Metrics/BlockLength:
  Exclude:
    - "lib/warped/emails/components/**/*.rb"
    - "spec/**/*"

Metrics/ParameterLists:
  Exclude:
    - "lib/warped/emails/components/**/*.rb"

Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/warped/queries/filter.rb"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - lib/warped/queries/filter.rb

Style/OptionalArguments:
  Exclude:
    - lib/warped/emails/components/button.rb
    - lib/warped/emails/components/link.rb
